title: "Lab. de Sistemas Ciberfísicos — PPGIA"
description: "Página oficial dos projetos de pesquisa, parcerias com a indústria e artigos publicados."
remote_theme: pages-themes/cayman@v0.2.0 # Tema base limpo do GitHub, sobreescrito pelo nosso CSS customizado
show_downloads: false